### ISSUE TITLE
Add pictures to README.md

### ISSUE THREAD

**Issue by sergii-tkachenko** [sergii-tkachenko/pagerbeauty#14]
<img width="971" alt="example-show-v0 0 4" src="https://user-images.githubusercontent.com/672669/46779296-1e233100-cce5-11e8-897c-b60f935e3ca8.png">

**Comment by sergii-tkachenko** [comment]
![pagerbeauty-v0 0 6-add-to-wallboard-blurred-optimized-d1-o2-2](https://user-images.githubusercontent.com/672669/46853316-ad0a7900-cdcb-11e8-80b3-ddedb7c8f2eb.gif)

**Comment by sergiitk** [comment]
<img width="700" alt="pb-700" src="https://user-images.githubusercontent.com/672669/50230229-429d2880-037a-11e9-85dc-0af2613187bf.png">

**Comment by sergiitk** [comment]
<img width="600" alt="pb-600" src="https://user-images.githubusercontent.com/672669/50230312-63657e00-037a-11e9-837b-fe3477880f04.png">

**Comment by sergiitk** [comment]
<img width="500" alt="pb-500" src="https://user-images.githubusercontent.com/672669/50230359-7ed08900-037a-11e9-8ce0-07098c61d906.png">

**Comment by sergiitk** [comment]
<img width="939" alt="pb-incident" src="https://user-images.githubusercontent.com/672669/52192943-95dc1500-281a-11e9-976f-094eed7e2126.png">

**Comment by sergiitk** [comment]
<img width="1024" alt="0 3 0" src="https://user-images.githubusercontent.com/672669/52192981-d63b9300-281a-11e9-8d51-d0982c205b78.png">

**Comment by sergiitk** [comment]
![add-to-grafana-800-10](https://user-images.githubusercontent.com/672669/52322269-75d95c80-29a6-11e9-9432-e3b420c13de1.gif)

**Comment by sergiitk** [comment]
![add-to-datadog-800-10](https://user-images.githubusercontent.com/672669/52323171-10876a80-29aa-11e9-8dcc-b0b7f421605e.gif)

**Comment by sergiitk** [comment]
![add-to-datadog-800-10](https://user-images.githubusercontent.com/672669/52323568-83ddac00-29ab-11e9-96ef-4f0612b0f36c.gif)

**Comment by sergiitk** [comment]
![add-to-datadog-gifenc-15](https://user-images.githubusercontent.com/672669/52325688-f6eb2080-29b3-11e9-8ce6-52296ddbcb0f.gif)

**Comment by sergiitk** [comment]
![add-to-datadog-gifenc-10-128](https://user-images.githubusercontent.com/672669/52326045-4d0c9380-29b5-11e9-9dc0-ca7402287c45.gif)

**Comment by sergiitk** [comment]
![add-to-grafana-800-15](https://user-images.githubusercontent.com/672669/52326212-d7ed8e00-29b5-11e9-8852-2c2adc536cc9.gif)

**Comment by sergiitk** [comment]
<img width="1690" alt="pb-v1 0 0-grafana" src="https://user-images.githubusercontent.com/672669/52326696-8d6d1100-29b7-11e9-9b92-12ac14f1d590.png">
